<template>
  <!-- <img src="../../assets/images/logo.png" class="object-fit-cover" style="height: 50px" /> -->
  <div class="loadingio-spinner-ellipsis-6lmlfi33ou6">
    <div class="ldio-p0tf8y27nqq">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script setup></script>

<style scoped>
@keyframes ldio-p0tf8y27nqq {
  0% {
    transform: translate(12px, 80px) scale(0);
  }
  25% {
    transform: translate(12px, 80px) scale(0);
  }
  50% {
    transform: translate(12px, 80px) scale(1);
  }
  75% {
    transform: translate(80px, 80px) scale(1);
  }
  100% {
    transform: translate(148px, 80px) scale(1);
  }
}
@keyframes ldio-p0tf8y27nqq-r {
  0% {
    transform: translate(148px, 80px) scale(1);
  }
  100% {
    transform: translate(148px, 80px) scale(0);
  }
}
@keyframes ldio-p0tf8y27nqq-c {
  0% {
    background: #ee0202;
  }
  25% {
    background: #ee0202;
  }
  50% {
    background: #ee0202;
  }
  75% {
    background: #ee0202;
  }
  100% {
    background: #e15b64;
  }
}
.ldio-p0tf8y27nqq div {
  position: absolute;
  width: 40px;
  height: 40px;
  border-radius: 50%;
  transform: translate(80px, 80px) scale(1);
  background: #ee0202;
  animation: ldio-p0tf8y27nqq 1s infinite cubic-bezier(0, 0.5, 0.5, 1);
}
.ldio-p0tf8y27nqq div:nth-child(1) {
  background: #ee0202;
  transform: translate(148px, 80px) scale(1);
  animation: ldio-p0tf8y27nqq-r 0.25s infinite cubic-bezier(0, 0.5, 0.5, 1), ldio-p0tf8y27nqq-c 1s infinite step-start;
}
.ldio-p0tf8y27nqq div:nth-child(2) {
  animation-delay: -0.25s;
  background: #ee0202;
}
.ldio-p0tf8y27nqq div:nth-child(3) {
  animation-delay: -0.5s;
  background: #ee0202;
}
.ldio-p0tf8y27nqq div:nth-child(4) {
  animation-delay: -0.75s;
  background: #ee0202;
}
.ldio-p0tf8y27nqq div:nth-child(5) {
  animation-delay: -1s;
  background: #ee0202;
}
.loadingio-spinner-ellipsis-6lmlfi33ou6 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-p0tf8y27nqq {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-p0tf8y27nqq div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
